// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: io/goodkind/celltunnel/control/v1/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TunnelControlService_Status_FullMethodName              = "/io.goodkind.celltunnel.control.v1.TunnelControlService/Status"
	TunnelControlService_Check_FullMethodName               = "/io.goodkind.celltunnel.control.v1.TunnelControlService/Check"
	TunnelControlService_StartTunnel_FullMethodName         = "/io.goodkind.celltunnel.control.v1.TunnelControlService/StartTunnel"
	TunnelControlService_StopTunnel_FullMethodName          = "/io.goodkind.celltunnel.control.v1.TunnelControlService/StopTunnel"
	TunnelControlService_StartRelayDiscovery_FullMethodName = "/io.goodkind.celltunnel.control.v1.TunnelControlService/StartRelayDiscovery"
	TunnelControlService_StopRelayDiscovery_FullMethodName  = "/io.goodkind.celltunnel.control.v1.TunnelControlService/StopRelayDiscovery"
	TunnelControlService_ListRelayServices_FullMethodName   = "/io.goodkind.celltunnel.control.v1.TunnelControlService/ListRelayServices"
	TunnelControlService_SelectRelayService_FullMethodName  = "/io.goodkind.celltunnel.control.v1.TunnelControlService/SelectRelayService"
)

// TunnelControlServiceClient is the client API for TunnelControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TunnelControlServiceClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	StartTunnel(ctx context.Context, in *StartTunnelRequest, opts ...grpc.CallOption) (*StartTunnelResponse, error)
	StopTunnel(ctx context.Context, in *StopTunnelRequest, opts ...grpc.CallOption) (*StopTunnelResponse, error)
	StartRelayDiscovery(ctx context.Context, in *StartRelayDiscoveryRequest, opts ...grpc.CallOption) (*StartRelayDiscoveryResponse, error)
	StopRelayDiscovery(ctx context.Context, in *StopRelayDiscoveryRequest, opts ...grpc.CallOption) (*StopRelayDiscoveryResponse, error)
	ListRelayServices(ctx context.Context, in *ListRelayServicesRequest, opts ...grpc.CallOption) (*ListRelayServicesResponse, error)
	SelectRelayService(ctx context.Context, in *SelectRelayServiceRequest, opts ...grpc.CallOption) (*SelectRelayServiceResponse, error)
}

type tunnelControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelControlServiceClient(cc grpc.ClientConnInterface) TunnelControlServiceClient {
	return &tunnelControlServiceClient{cc}
}

func (c *tunnelControlServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TunnelControlService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelControlServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, TunnelControlService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelControlServiceClient) StartTunnel(ctx context.Context, in *StartTunnelRequest, opts ...grpc.CallOption) (*StartTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTunnelResponse)
	err := c.cc.Invoke(ctx, TunnelControlService_StartTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelControlServiceClient) StopTunnel(ctx context.Context, in *StopTunnelRequest, opts ...grpc.CallOption) (*StopTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopTunnelResponse)
	err := c.cc.Invoke(ctx, TunnelControlService_StopTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelControlServiceClient) StartRelayDiscovery(ctx context.Context, in *StartRelayDiscoveryRequest, opts ...grpc.CallOption) (*StartRelayDiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRelayDiscoveryResponse)
	err := c.cc.Invoke(ctx, TunnelControlService_StartRelayDiscovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelControlServiceClient) StopRelayDiscovery(ctx context.Context, in *StopRelayDiscoveryRequest, opts ...grpc.CallOption) (*StopRelayDiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRelayDiscoveryResponse)
	err := c.cc.Invoke(ctx, TunnelControlService_StopRelayDiscovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelControlServiceClient) ListRelayServices(ctx context.Context, in *ListRelayServicesRequest, opts ...grpc.CallOption) (*ListRelayServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRelayServicesResponse)
	err := c.cc.Invoke(ctx, TunnelControlService_ListRelayServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelControlServiceClient) SelectRelayService(ctx context.Context, in *SelectRelayServiceRequest, opts ...grpc.CallOption) (*SelectRelayServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectRelayServiceResponse)
	err := c.cc.Invoke(ctx, TunnelControlService_SelectRelayService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TunnelControlServiceServer is the server API for TunnelControlService service.
// All implementations must embed UnimplementedTunnelControlServiceServer
// for forward compatibility.
type TunnelControlServiceServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	StartTunnel(context.Context, *StartTunnelRequest) (*StartTunnelResponse, error)
	StopTunnel(context.Context, *StopTunnelRequest) (*StopTunnelResponse, error)
	StartRelayDiscovery(context.Context, *StartRelayDiscoveryRequest) (*StartRelayDiscoveryResponse, error)
	StopRelayDiscovery(context.Context, *StopRelayDiscoveryRequest) (*StopRelayDiscoveryResponse, error)
	ListRelayServices(context.Context, *ListRelayServicesRequest) (*ListRelayServicesResponse, error)
	SelectRelayService(context.Context, *SelectRelayServiceRequest) (*SelectRelayServiceResponse, error)
	mustEmbedUnimplementedTunnelControlServiceServer()
}

// UnimplementedTunnelControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTunnelControlServiceServer struct{}

func (UnimplementedTunnelControlServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedTunnelControlServiceServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedTunnelControlServiceServer) StartTunnel(context.Context, *StartTunnelRequest) (*StartTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTunnel not implemented")
}
func (UnimplementedTunnelControlServiceServer) StopTunnel(context.Context, *StopTunnelRequest) (*StopTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTunnel not implemented")
}
func (UnimplementedTunnelControlServiceServer) StartRelayDiscovery(context.Context, *StartRelayDiscoveryRequest) (*StartRelayDiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRelayDiscovery not implemented")
}
func (UnimplementedTunnelControlServiceServer) StopRelayDiscovery(context.Context, *StopRelayDiscoveryRequest) (*StopRelayDiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRelayDiscovery not implemented")
}
func (UnimplementedTunnelControlServiceServer) ListRelayServices(context.Context, *ListRelayServicesRequest) (*ListRelayServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRelayServices not implemented")
}
func (UnimplementedTunnelControlServiceServer) SelectRelayService(context.Context, *SelectRelayServiceRequest) (*SelectRelayServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectRelayService not implemented")
}
func (UnimplementedTunnelControlServiceServer) mustEmbedUnimplementedTunnelControlServiceServer() {}
func (UnimplementedTunnelControlServiceServer) testEmbeddedByValue()                              {}

// UnsafeTunnelControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelControlServiceServer will
// result in compilation errors.
type UnsafeTunnelControlServiceServer interface {
	mustEmbedUnimplementedTunnelControlServiceServer()
}

func RegisterTunnelControlServiceServer(s grpc.ServiceRegistrar, srv TunnelControlServiceServer) {
	// If the following call panics, it indicates UnimplementedTunnelControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TunnelControlService_ServiceDesc, srv)
}

func _TunnelControlService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelControlServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelControlService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelControlServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelControlService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelControlServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelControlService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelControlServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelControlService_StartTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelControlServiceServer).StartTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelControlService_StartTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelControlServiceServer).StartTunnel(ctx, req.(*StartTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelControlService_StopTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelControlServiceServer).StopTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelControlService_StopTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelControlServiceServer).StopTunnel(ctx, req.(*StopTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelControlService_StartRelayDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRelayDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelControlServiceServer).StartRelayDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelControlService_StartRelayDiscovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelControlServiceServer).StartRelayDiscovery(ctx, req.(*StartRelayDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelControlService_StopRelayDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRelayDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelControlServiceServer).StopRelayDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelControlService_StopRelayDiscovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelControlServiceServer).StopRelayDiscovery(ctx, req.(*StopRelayDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelControlService_ListRelayServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRelayServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelControlServiceServer).ListRelayServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelControlService_ListRelayServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelControlServiceServer).ListRelayServices(ctx, req.(*ListRelayServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelControlService_SelectRelayService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRelayServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelControlServiceServer).SelectRelayService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelControlService_SelectRelayService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelControlServiceServer).SelectRelayService(ctx, req.(*SelectRelayServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TunnelControlService_ServiceDesc is the grpc.ServiceDesc for TunnelControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.goodkind.celltunnel.control.v1.TunnelControlService",
	HandlerType: (*TunnelControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _TunnelControlService_Status_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _TunnelControlService_Check_Handler,
		},
		{
			MethodName: "StartTunnel",
			Handler:    _TunnelControlService_StartTunnel_Handler,
		},
		{
			MethodName: "StopTunnel",
			Handler:    _TunnelControlService_StopTunnel_Handler,
		},
		{
			MethodName: "StartRelayDiscovery",
			Handler:    _TunnelControlService_StartRelayDiscovery_Handler,
		},
		{
			MethodName: "StopRelayDiscovery",
			Handler:    _TunnelControlService_StopRelayDiscovery_Handler,
		},
		{
			MethodName: "ListRelayServices",
			Handler:    _TunnelControlService_ListRelayServices_Handler,
		},
		{
			MethodName: "SelectRelayService",
			Handler:    _TunnelControlService_SelectRelayService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "io/goodkind/celltunnel/control/v1/control.proto",
}
