// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: io/goodkind/celltunnel/control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressFamily int32

const (
	AddressFamily_ADDRESS_FAMILY_UNSPECIFIED AddressFamily = 0
	AddressFamily_ADDRESS_FAMILY_IPV4        AddressFamily = 1
	AddressFamily_ADDRESS_FAMILY_IPV6        AddressFamily = 2
)

// Enum value maps for AddressFamily.
var (
	AddressFamily_name = map[int32]string{
		0: "ADDRESS_FAMILY_UNSPECIFIED",
		1: "ADDRESS_FAMILY_IPV4",
		2: "ADDRESS_FAMILY_IPV6",
	}
	AddressFamily_value = map[string]int32{
		"ADDRESS_FAMILY_UNSPECIFIED": 0,
		"ADDRESS_FAMILY_IPV4":        1,
		"ADDRESS_FAMILY_IPV6":        2,
	}
)

func (x AddressFamily) Enum() *AddressFamily {
	p := new(AddressFamily)
	*p = x
	return p
}

func (x AddressFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_io_goodkind_celltunnel_control_v1_control_proto_enumTypes[0].Descriptor()
}

func (AddressFamily) Type() protoreflect.EnumType {
	return &file_io_goodkind_celltunnel_control_v1_control_proto_enumTypes[0]
}

func (x AddressFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressFamily.Descriptor instead.
func (AddressFamily) EnumDescriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{0}
}

type RouteState int32

const (
	RouteState_ROUTE_STATE_UNSPECIFIED   RouteState = 0
	RouteState_ROUTE_STATE_NOT_INSTALLED RouteState = 1
	RouteState_ROUTE_STATE_INSTALLED     RouteState = 2
)

// Enum value maps for RouteState.
var (
	RouteState_name = map[int32]string{
		0: "ROUTE_STATE_UNSPECIFIED",
		1: "ROUTE_STATE_NOT_INSTALLED",
		2: "ROUTE_STATE_INSTALLED",
	}
	RouteState_value = map[string]int32{
		"ROUTE_STATE_UNSPECIFIED":   0,
		"ROUTE_STATE_NOT_INSTALLED": 1,
		"ROUTE_STATE_INSTALLED":     2,
	}
)

func (x RouteState) Enum() *RouteState {
	p := new(RouteState)
	*p = x
	return p
}

func (x RouteState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteState) Descriptor() protoreflect.EnumDescriptor {
	return file_io_goodkind_celltunnel_control_v1_control_proto_enumTypes[1].Descriptor()
}

func (RouteState) Type() protoreflect.EnumType {
	return &file_io_goodkind_celltunnel_control_v1_control_proto_enumTypes[1]
}

func (x RouteState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteState.Descriptor instead.
func (RouteState) EnumDescriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{1}
}

type PeerState int32

const (
	PeerState_PEER_STATE_UNSPECIFIED          PeerState = 0
	PeerState_PEER_STATE_NOT_SELECTED         PeerState = 1
	PeerState_PEER_STATE_RELAY_SELECTED       PeerState = 2
	PeerState_PEER_STATE_WIREGUARD_CONFIGURED PeerState = 3
)

// Enum value maps for PeerState.
var (
	PeerState_name = map[int32]string{
		0: "PEER_STATE_UNSPECIFIED",
		1: "PEER_STATE_NOT_SELECTED",
		2: "PEER_STATE_RELAY_SELECTED",
		3: "PEER_STATE_WIREGUARD_CONFIGURED",
	}
	PeerState_value = map[string]int32{
		"PEER_STATE_UNSPECIFIED":          0,
		"PEER_STATE_NOT_SELECTED":         1,
		"PEER_STATE_RELAY_SELECTED":       2,
		"PEER_STATE_WIREGUARD_CONFIGURED": 3,
	}
)

func (x PeerState) Enum() *PeerState {
	p := new(PeerState)
	*p = x
	return p
}

func (x PeerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerState) Descriptor() protoreflect.EnumDescriptor {
	return file_io_goodkind_celltunnel_control_v1_control_proto_enumTypes[2].Descriptor()
}

func (PeerState) Type() protoreflect.EnumType {
	return &file_io_goodkind_celltunnel_control_v1_control_proto_enumTypes[2]
}

func (x PeerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerState.Descriptor instead.
func (PeerState) EnumDescriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{2}
}

type DiscoveryPhase int32

const (
	DiscoveryPhase_DISCOVERY_PHASE_UNSPECIFIED DiscoveryPhase = 0
	DiscoveryPhase_DISCOVERY_PHASE_STOPPED     DiscoveryPhase = 1
	DiscoveryPhase_DISCOVERY_PHASE_BROWSING    DiscoveryPhase = 2
	DiscoveryPhase_DISCOVERY_PHASE_READY       DiscoveryPhase = 3
	DiscoveryPhase_DISCOVERY_PHASE_FAILED      DiscoveryPhase = 4
)

// Enum value maps for DiscoveryPhase.
var (
	DiscoveryPhase_name = map[int32]string{
		0: "DISCOVERY_PHASE_UNSPECIFIED",
		1: "DISCOVERY_PHASE_STOPPED",
		2: "DISCOVERY_PHASE_BROWSING",
		3: "DISCOVERY_PHASE_READY",
		4: "DISCOVERY_PHASE_FAILED",
	}
	DiscoveryPhase_value = map[string]int32{
		"DISCOVERY_PHASE_UNSPECIFIED": 0,
		"DISCOVERY_PHASE_STOPPED":     1,
		"DISCOVERY_PHASE_BROWSING":    2,
		"DISCOVERY_PHASE_READY":       3,
		"DISCOVERY_PHASE_FAILED":      4,
	}
)

func (x DiscoveryPhase) Enum() *DiscoveryPhase {
	p := new(DiscoveryPhase)
	*p = x
	return p
}

func (x DiscoveryPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscoveryPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_io_goodkind_celltunnel_control_v1_control_proto_enumTypes[3].Descriptor()
}

func (DiscoveryPhase) Type() protoreflect.EnumType {
	return &file_io_goodkind_celltunnel_control_v1_control_proto_enumTypes[3]
}

func (x DiscoveryPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscoveryPhase.Descriptor instead.
func (DiscoveryPhase) EnumDescriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{3}
}

type ControlErrorCode int32

const (
	ControlErrorCode_CONTROL_ERROR_CODE_UNSPECIFIED                   ControlErrorCode = 0
	ControlErrorCode_CONTROL_ERROR_CODE_MISSING_WIREGUARD_CONFIG_PATH ControlErrorCode = 1
	ControlErrorCode_CONTROL_ERROR_CODE_RELAY_SELECTION_REQUIRED      ControlErrorCode = 2
	ControlErrorCode_CONTROL_ERROR_CODE_RELAY_SERVICE_NOT_FOUND       ControlErrorCode = 3
	ControlErrorCode_CONTROL_ERROR_CODE_DISCOVERY_UNAVAILABLE         ControlErrorCode = 4
	ControlErrorCode_CONTROL_ERROR_CODE_INVALID_RELAY_ENDPOINT        ControlErrorCode = 5
	ControlErrorCode_CONTROL_ERROR_CODE_RUNTIME_START_FAILURE         ControlErrorCode = 6
	ControlErrorCode_CONTROL_ERROR_CODE_INTERNAL                      ControlErrorCode = 7
)

// Enum value maps for ControlErrorCode.
var (
	ControlErrorCode_name = map[int32]string{
		0: "CONTROL_ERROR_CODE_UNSPECIFIED",
		1: "CONTROL_ERROR_CODE_MISSING_WIREGUARD_CONFIG_PATH",
		2: "CONTROL_ERROR_CODE_RELAY_SELECTION_REQUIRED",
		3: "CONTROL_ERROR_CODE_RELAY_SERVICE_NOT_FOUND",
		4: "CONTROL_ERROR_CODE_DISCOVERY_UNAVAILABLE",
		5: "CONTROL_ERROR_CODE_INVALID_RELAY_ENDPOINT",
		6: "CONTROL_ERROR_CODE_RUNTIME_START_FAILURE",
		7: "CONTROL_ERROR_CODE_INTERNAL",
	}
	ControlErrorCode_value = map[string]int32{
		"CONTROL_ERROR_CODE_UNSPECIFIED":                   0,
		"CONTROL_ERROR_CODE_MISSING_WIREGUARD_CONFIG_PATH": 1,
		"CONTROL_ERROR_CODE_RELAY_SELECTION_REQUIRED":      2,
		"CONTROL_ERROR_CODE_RELAY_SERVICE_NOT_FOUND":       3,
		"CONTROL_ERROR_CODE_DISCOVERY_UNAVAILABLE":         4,
		"CONTROL_ERROR_CODE_INVALID_RELAY_ENDPOINT":        5,
		"CONTROL_ERROR_CODE_RUNTIME_START_FAILURE":         6,
		"CONTROL_ERROR_CODE_INTERNAL":                      7,
	}
)

func (x ControlErrorCode) Enum() *ControlErrorCode {
	p := new(ControlErrorCode)
	*p = x
	return p
}

func (x ControlErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_io_goodkind_celltunnel_control_v1_control_proto_enumTypes[4].Descriptor()
}

func (ControlErrorCode) Type() protoreflect.EnumType {
	return &file_io_goodkind_celltunnel_control_v1_control_proto_enumTypes[4]
}

func (x ControlErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlErrorCode.Descriptor instead.
func (ControlErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{4}
}

type ControlError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ControlErrorCode       `protobuf:"varint,1,opt,name=code,proto3,enum=io.goodkind.celltunnel.control.v1.ControlErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlError) Reset() {
	*x = ControlError{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlError) ProtoMessage() {}

func (x *ControlError) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlError.ProtoReflect.Descriptor instead.
func (*ControlError) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlError) GetCode() ControlErrorCode {
	if x != nil {
		return x.Code
	}
	return ControlErrorCode_CONTROL_ERROR_CODE_UNSPECIFIED
}

func (x *ControlError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RelayEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	AddressFamily AddressFamily          `protobuf:"varint,3,opt,name=address_family,json=addressFamily,proto3,enum=io.goodkind.celltunnel.control.v1.AddressFamily" json:"address_family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayEndpoint) Reset() {
	*x = RelayEndpoint{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayEndpoint) ProtoMessage() {}

func (x *RelayEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayEndpoint.ProtoReflect.Descriptor instead.
func (*RelayEndpoint) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *RelayEndpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RelayEndpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RelayEndpoint) GetAddressFamily() AddressFamily {
	if x != nil {
		return x.AddressFamily
	}
	return AddressFamily_ADDRESS_FAMILY_UNSPECIFIED
}

type RelayServiceIdentity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceId      string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName    string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceType    string                 `protobuf:"bytes,3,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Domain         string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	InterfaceIndex uint32                 `protobuf:"varint,5,opt,name=interface_index,json=interfaceIndex,proto3" json:"interface_index,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RelayServiceIdentity) Reset() {
	*x = RelayServiceIdentity{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayServiceIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayServiceIdentity) ProtoMessage() {}

func (x *RelayServiceIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayServiceIdentity.ProtoReflect.Descriptor instead.
func (*RelayServiceIdentity) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *RelayServiceIdentity) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RelayServiceIdentity) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RelayServiceIdentity) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *RelayServiceIdentity) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RelayServiceIdentity) GetInterfaceIndex() uint32 {
	if x != nil {
		return x.InterfaceIndex
	}
	return 0
}

type RelayService struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Identity          *RelayServiceIdentity  `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	HostName          string                 `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Endpoints         []*RelayEndpoint       `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	PreferredEndpoint *RelayEndpoint         `protobuf:"bytes,4,opt,name=preferred_endpoint,json=preferredEndpoint,proto3" json:"preferred_endpoint,omitempty"`
	IsSelected        bool                   `protobuf:"varint,5,opt,name=is_selected,json=isSelected,proto3" json:"is_selected,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RelayService) Reset() {
	*x = RelayService{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayService) ProtoMessage() {}

func (x *RelayService) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayService.ProtoReflect.Descriptor instead.
func (*RelayService) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *RelayService) GetIdentity() *RelayServiceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *RelayService) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *RelayService) GetEndpoints() []*RelayEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *RelayService) GetPreferredEndpoint() *RelayEndpoint {
	if x != nil {
		return x.PreferredEndpoint
	}
	return nil
}

func (x *RelayService) GetIsSelected() bool {
	if x != nil {
		return x.IsSelected
	}
	return false
}

type DiscoveryState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Phase             DiscoveryPhase         `protobuf:"varint,1,opt,name=phase,proto3,enum=io.goodkind.celltunnel.control.v1.DiscoveryPhase" json:"phase,omitempty"`
	Services          []*RelayService        `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	SelectedServiceId string                 `protobuf:"bytes,3,opt,name=selected_service_id,json=selectedServiceId,proto3" json:"selected_service_id,omitempty"`
	SelectedEndpoint  *RelayEndpoint         `protobuf:"bytes,4,opt,name=selected_endpoint,json=selectedEndpoint,proto3" json:"selected_endpoint,omitempty"`
	LastError         *ControlError          `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DiscoveryState) Reset() {
	*x = DiscoveryState{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryState) ProtoMessage() {}

func (x *DiscoveryState) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryState.ProtoReflect.Descriptor instead.
func (*DiscoveryState) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoveryState) GetPhase() DiscoveryPhase {
	if x != nil {
		return x.Phase
	}
	return DiscoveryPhase_DISCOVERY_PHASE_UNSPECIFIED
}

func (x *DiscoveryState) GetServices() []*RelayService {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *DiscoveryState) GetSelectedServiceId() string {
	if x != nil {
		return x.SelectedServiceId
	}
	return ""
}

func (x *DiscoveryState) GetSelectedEndpoint() *RelayEndpoint {
	if x != nil {
		return x.SelectedEndpoint
	}
	return nil
}

func (x *DiscoveryState) GetLastError() *ControlError {
	if x != nil {
		return x.LastError
	}
	return nil
}

type RouteStateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         RouteState             `protobuf:"varint,1,opt,name=state,proto3,enum=io.goodkind.celltunnel.control.v1.RouteState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteStateSnapshot) Reset() {
	*x = RouteStateSnapshot{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteStateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteStateSnapshot) ProtoMessage() {}

func (x *RouteStateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteStateSnapshot.ProtoReflect.Descriptor instead.
func (*RouteStateSnapshot) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *RouteStateSnapshot) GetState() RouteState {
	if x != nil {
		return x.State
	}
	return RouteState_ROUTE_STATE_UNSPECIFIED
}

type PeerStateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         PeerState              `protobuf:"varint,1,opt,name=state,proto3,enum=io.goodkind.celltunnel.control.v1.PeerState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerStateSnapshot) Reset() {
	*x = PeerStateSnapshot{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStateSnapshot) ProtoMessage() {}

func (x *PeerStateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStateSnapshot.ProtoReflect.Descriptor instead.
func (*PeerStateSnapshot) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *PeerStateSnapshot) GetState() PeerState {
	if x != nil {
		return x.State
	}
	return PeerState_PEER_STATE_UNSPECIFIED
}

type TunnelStartSettings struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WireGuardConfigPath string                 `protobuf:"bytes,1,opt,name=wire_guard_config_path,json=wireGuardConfigPath,proto3" json:"wire_guard_config_path,omitempty"`
	RelayEndpoint       *RelayEndpoint         `protobuf:"bytes,2,opt,name=relay_endpoint,json=relayEndpoint,proto3" json:"relay_endpoint,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TunnelStartSettings) Reset() {
	*x = TunnelStartSettings{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelStartSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelStartSettings) ProtoMessage() {}

func (x *TunnelStartSettings) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelStartSettings.ProtoReflect.Descriptor instead.
func (*TunnelStartSettings) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *TunnelStartSettings) GetWireGuardConfigPath() string {
	if x != nil {
		return x.WireGuardConfigPath
	}
	return ""
}

func (x *TunnelStartSettings) GetRelayEndpoint() *RelayEndpoint {
	if x != nil {
		return x.RelayEndpoint
	}
	return nil
}

type DaemonStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Running             bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Route               *RouteStateSnapshot    `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	Peer                *PeerStateSnapshot     `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	Ipv4Address         string                 `protobuf:"bytes,4,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	Ipv6Address         string                 `protobuf:"bytes,5,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	LastError           *ControlError          `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Discovery           *DiscoveryState        `protobuf:"bytes,7,opt,name=discovery,proto3" json:"discovery,omitempty"`
	ActiveRelayEndpoint *RelayEndpoint         `protobuf:"bytes,8,opt,name=active_relay_endpoint,json=activeRelayEndpoint,proto3" json:"active_relay_endpoint,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DaemonStatus) Reset() {
	*x = DaemonStatus{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatus) ProtoMessage() {}

func (x *DaemonStatus) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatus.ProtoReflect.Descriptor instead.
func (*DaemonStatus) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *DaemonStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *DaemonStatus) GetRoute() *RouteStateSnapshot {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *DaemonStatus) GetPeer() *PeerStateSnapshot {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *DaemonStatus) GetIpv4Address() string {
	if x != nil {
		return x.Ipv4Address
	}
	return ""
}

func (x *DaemonStatus) GetIpv6Address() string {
	if x != nil {
		return x.Ipv6Address
	}
	return ""
}

func (x *DaemonStatus) GetLastError() *ControlError {
	if x != nil {
		return x.LastError
	}
	return nil
}

func (x *DaemonStatus) GetDiscovery() *DiscoveryState {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *DaemonStatus) GetActiveRelayEndpoint() *RelayEndpoint {
	if x != nil {
		return x.ActiveRelayEndpoint
	}
	return nil
}

type EnvironmentCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentCheck) Reset() {
	*x = EnvironmentCheck{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentCheck) ProtoMessage() {}

func (x *EnvironmentCheck) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentCheck.ProtoReflect.Descriptor instead.
func (*EnvironmentCheck) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *EnvironmentCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvironmentCheck) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EnvironmentReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*EnvironmentCheck    `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentReport) Reset() {
	*x = EnvironmentReport{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentReport) ProtoMessage() {}

func (x *EnvironmentReport) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentReport.ProtoReflect.Descriptor instead.
func (*EnvironmentReport) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *EnvironmentReport) GetChecks() []*EnvironmentCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{11}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*StatusResponse_Status
	//	*StatusResponse_Error
	Result        isStatusResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *StatusResponse) GetResult() isStatusResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StatusResponse) GetStatus() *DaemonStatus {
	if x != nil {
		if x, ok := x.Result.(*StatusResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *StatusResponse) GetError() *ControlError {
	if x != nil {
		if x, ok := x.Result.(*StatusResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStatusResponse_Result interface {
	isStatusResponse_Result()
}

type StatusResponse_Status struct {
	Status *DaemonStatus `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type StatusResponse_Error struct {
	Error *ControlError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StatusResponse_Status) isStatusResponse_Result() {}

func (*StatusResponse_Error) isStatusResponse_Result() {}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{13}
}

type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CheckResponse_Report
	//	*CheckResponse_Error
	Result        isCheckResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *CheckResponse) GetResult() isCheckResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CheckResponse) GetReport() *EnvironmentReport {
	if x != nil {
		if x, ok := x.Result.(*CheckResponse_Report); ok {
			return x.Report
		}
	}
	return nil
}

func (x *CheckResponse) GetError() *ControlError {
	if x != nil {
		if x, ok := x.Result.(*CheckResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCheckResponse_Result interface {
	isCheckResponse_Result()
}

type CheckResponse_Report struct {
	Report *EnvironmentReport `protobuf:"bytes,1,opt,name=report,proto3,oneof"`
}

type CheckResponse_Error struct {
	Error *ControlError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CheckResponse_Report) isCheckResponse_Result() {}

func (*CheckResponse_Error) isCheckResponse_Result() {}

type StartTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *TunnelStartSettings   `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTunnelRequest) Reset() {
	*x = StartTunnelRequest{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTunnelRequest) ProtoMessage() {}

func (x *StartTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTunnelRequest.ProtoReflect.Descriptor instead.
func (*StartTunnelRequest) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *StartTunnelRequest) GetSettings() *TunnelStartSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type StartTunnelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*StartTunnelResponse_Status
	//	*StartTunnelResponse_Error
	Result        isStartTunnelResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTunnelResponse) Reset() {
	*x = StartTunnelResponse{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTunnelResponse) ProtoMessage() {}

func (x *StartTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTunnelResponse.ProtoReflect.Descriptor instead.
func (*StartTunnelResponse) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *StartTunnelResponse) GetResult() isStartTunnelResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StartTunnelResponse) GetStatus() *DaemonStatus {
	if x != nil {
		if x, ok := x.Result.(*StartTunnelResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *StartTunnelResponse) GetError() *ControlError {
	if x != nil {
		if x, ok := x.Result.(*StartTunnelResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStartTunnelResponse_Result interface {
	isStartTunnelResponse_Result()
}

type StartTunnelResponse_Status struct {
	Status *DaemonStatus `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type StartTunnelResponse_Error struct {
	Error *ControlError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StartTunnelResponse_Status) isStartTunnelResponse_Result() {}

func (*StartTunnelResponse_Error) isStartTunnelResponse_Result() {}

type StopTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTunnelRequest) Reset() {
	*x = StopTunnelRequest{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTunnelRequest) ProtoMessage() {}

func (x *StopTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTunnelRequest.ProtoReflect.Descriptor instead.
func (*StopTunnelRequest) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{17}
}

type StopTunnelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*StopTunnelResponse_Status
	//	*StopTunnelResponse_Error
	Result        isStopTunnelResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTunnelResponse) Reset() {
	*x = StopTunnelResponse{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTunnelResponse) ProtoMessage() {}

func (x *StopTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTunnelResponse.ProtoReflect.Descriptor instead.
func (*StopTunnelResponse) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *StopTunnelResponse) GetResult() isStopTunnelResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StopTunnelResponse) GetStatus() *DaemonStatus {
	if x != nil {
		if x, ok := x.Result.(*StopTunnelResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *StopTunnelResponse) GetError() *ControlError {
	if x != nil {
		if x, ok := x.Result.(*StopTunnelResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStopTunnelResponse_Result interface {
	isStopTunnelResponse_Result()
}

type StopTunnelResponse_Status struct {
	Status *DaemonStatus `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type StopTunnelResponse_Error struct {
	Error *ControlError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StopTunnelResponse_Status) isStopTunnelResponse_Result() {}

func (*StopTunnelResponse_Error) isStopTunnelResponse_Result() {}

type StartRelayDiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRelayDiscoveryRequest) Reset() {
	*x = StartRelayDiscoveryRequest{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRelayDiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRelayDiscoveryRequest) ProtoMessage() {}

func (x *StartRelayDiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRelayDiscoveryRequest.ProtoReflect.Descriptor instead.
func (*StartRelayDiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{19}
}

type StartRelayDiscoveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*StartRelayDiscoveryResponse_Discovery
	//	*StartRelayDiscoveryResponse_Error
	Result        isStartRelayDiscoveryResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRelayDiscoveryResponse) Reset() {
	*x = StartRelayDiscoveryResponse{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRelayDiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRelayDiscoveryResponse) ProtoMessage() {}

func (x *StartRelayDiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRelayDiscoveryResponse.ProtoReflect.Descriptor instead.
func (*StartRelayDiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{20}
}

func (x *StartRelayDiscoveryResponse) GetResult() isStartRelayDiscoveryResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StartRelayDiscoveryResponse) GetDiscovery() *DiscoveryState {
	if x != nil {
		if x, ok := x.Result.(*StartRelayDiscoveryResponse_Discovery); ok {
			return x.Discovery
		}
	}
	return nil
}

func (x *StartRelayDiscoveryResponse) GetError() *ControlError {
	if x != nil {
		if x, ok := x.Result.(*StartRelayDiscoveryResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStartRelayDiscoveryResponse_Result interface {
	isStartRelayDiscoveryResponse_Result()
}

type StartRelayDiscoveryResponse_Discovery struct {
	Discovery *DiscoveryState `protobuf:"bytes,1,opt,name=discovery,proto3,oneof"`
}

type StartRelayDiscoveryResponse_Error struct {
	Error *ControlError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StartRelayDiscoveryResponse_Discovery) isStartRelayDiscoveryResponse_Result() {}

func (*StartRelayDiscoveryResponse_Error) isStartRelayDiscoveryResponse_Result() {}

type StopRelayDiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRelayDiscoveryRequest) Reset() {
	*x = StopRelayDiscoveryRequest{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRelayDiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRelayDiscoveryRequest) ProtoMessage() {}

func (x *StopRelayDiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRelayDiscoveryRequest.ProtoReflect.Descriptor instead.
func (*StopRelayDiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{21}
}

type StopRelayDiscoveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*StopRelayDiscoveryResponse_Discovery
	//	*StopRelayDiscoveryResponse_Error
	Result        isStopRelayDiscoveryResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRelayDiscoveryResponse) Reset() {
	*x = StopRelayDiscoveryResponse{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRelayDiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRelayDiscoveryResponse) ProtoMessage() {}

func (x *StopRelayDiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRelayDiscoveryResponse.ProtoReflect.Descriptor instead.
func (*StopRelayDiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{22}
}

func (x *StopRelayDiscoveryResponse) GetResult() isStopRelayDiscoveryResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StopRelayDiscoveryResponse) GetDiscovery() *DiscoveryState {
	if x != nil {
		if x, ok := x.Result.(*StopRelayDiscoveryResponse_Discovery); ok {
			return x.Discovery
		}
	}
	return nil
}

func (x *StopRelayDiscoveryResponse) GetError() *ControlError {
	if x != nil {
		if x, ok := x.Result.(*StopRelayDiscoveryResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStopRelayDiscoveryResponse_Result interface {
	isStopRelayDiscoveryResponse_Result()
}

type StopRelayDiscoveryResponse_Discovery struct {
	Discovery *DiscoveryState `protobuf:"bytes,1,opt,name=discovery,proto3,oneof"`
}

type StopRelayDiscoveryResponse_Error struct {
	Error *ControlError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StopRelayDiscoveryResponse_Discovery) isStopRelayDiscoveryResponse_Result() {}

func (*StopRelayDiscoveryResponse_Error) isStopRelayDiscoveryResponse_Result() {}

type ListRelayServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelayServicesRequest) Reset() {
	*x = ListRelayServicesRequest{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelayServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelayServicesRequest) ProtoMessage() {}

func (x *ListRelayServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelayServicesRequest.ProtoReflect.Descriptor instead.
func (*ListRelayServicesRequest) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{23}
}

type ListRelayServicesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ListRelayServicesResponse_Discovery
	//	*ListRelayServicesResponse_Error
	Result        isListRelayServicesResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelayServicesResponse) Reset() {
	*x = ListRelayServicesResponse{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelayServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelayServicesResponse) ProtoMessage() {}

func (x *ListRelayServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelayServicesResponse.ProtoReflect.Descriptor instead.
func (*ListRelayServicesResponse) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{24}
}

func (x *ListRelayServicesResponse) GetResult() isListRelayServicesResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListRelayServicesResponse) GetDiscovery() *DiscoveryState {
	if x != nil {
		if x, ok := x.Result.(*ListRelayServicesResponse_Discovery); ok {
			return x.Discovery
		}
	}
	return nil
}

func (x *ListRelayServicesResponse) GetError() *ControlError {
	if x != nil {
		if x, ok := x.Result.(*ListRelayServicesResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isListRelayServicesResponse_Result interface {
	isListRelayServicesResponse_Result()
}

type ListRelayServicesResponse_Discovery struct {
	Discovery *DiscoveryState `protobuf:"bytes,1,opt,name=discovery,proto3,oneof"`
}

type ListRelayServicesResponse_Error struct {
	Error *ControlError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListRelayServicesResponse_Discovery) isListRelayServicesResponse_Result() {}

func (*ListRelayServicesResponse_Error) isListRelayServicesResponse_Result() {}

type SelectRelayServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRelayServiceRequest) Reset() {
	*x = SelectRelayServiceRequest{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRelayServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRelayServiceRequest) ProtoMessage() {}

func (x *SelectRelayServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRelayServiceRequest.ProtoReflect.Descriptor instead.
func (*SelectRelayServiceRequest) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{25}
}

func (x *SelectRelayServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type SelectRelayServiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*SelectRelayServiceResponse_Discovery
	//	*SelectRelayServiceResponse_Error
	Result        isSelectRelayServiceResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRelayServiceResponse) Reset() {
	*x = SelectRelayServiceResponse{}
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRelayServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRelayServiceResponse) ProtoMessage() {}

func (x *SelectRelayServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRelayServiceResponse.ProtoReflect.Descriptor instead.
func (*SelectRelayServiceResponse) Descriptor() ([]byte, []int) {
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP(), []int{26}
}

func (x *SelectRelayServiceResponse) GetResult() isSelectRelayServiceResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SelectRelayServiceResponse) GetDiscovery() *DiscoveryState {
	if x != nil {
		if x, ok := x.Result.(*SelectRelayServiceResponse_Discovery); ok {
			return x.Discovery
		}
	}
	return nil
}

func (x *SelectRelayServiceResponse) GetError() *ControlError {
	if x != nil {
		if x, ok := x.Result.(*SelectRelayServiceResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSelectRelayServiceResponse_Result interface {
	isSelectRelayServiceResponse_Result()
}

type SelectRelayServiceResponse_Discovery struct {
	Discovery *DiscoveryState `protobuf:"bytes,1,opt,name=discovery,proto3,oneof"`
}

type SelectRelayServiceResponse_Error struct {
	Error *ControlError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*SelectRelayServiceResponse_Discovery) isSelectRelayServiceResponse_Result() {}

func (*SelectRelayServiceResponse_Error) isSelectRelayServiceResponse_Result() {}

var File_io_goodkind_celltunnel_control_v1_control_proto protoreflect.FileDescriptor

const file_io_goodkind_celltunnel_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"/io/goodkind/celltunnel/control/v1/control.proto\x12!io.goodkind.celltunnel.control.v1\"q\n" +
	"\fControlError\x12G\n" +
	"\x04code\x18\x01 \x01(\x0e23.io.goodkind.celltunnel.control.v1.ControlErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x90\x01\n" +
	"\rRelayEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12W\n" +
	"\x0eaddress_family\x18\x03 \x01(\x0e20.io.goodkind.celltunnel.control.v1.AddressFamilyR\raddressFamily\"\xbc\x01\n" +
	"\x14RelayServiceIdentity\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12!\n" +
	"\fservice_type\x18\x03 \x01(\tR\vserviceType\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12'\n" +
	"\x0finterface_index\x18\x05 \x01(\rR\x0einterfaceIndex\"\xd2\x02\n" +
	"\fRelayService\x12S\n" +
	"\bidentity\x18\x01 \x01(\v27.io.goodkind.celltunnel.control.v1.RelayServiceIdentityR\bidentity\x12\x1b\n" +
	"\thost_name\x18\x02 \x01(\tR\bhostName\x12N\n" +
	"\tendpoints\x18\x03 \x03(\v20.io.goodkind.celltunnel.control.v1.RelayEndpointR\tendpoints\x12_\n" +
	"\x12preferred_endpoint\x18\x04 \x01(\v20.io.goodkind.celltunnel.control.v1.RelayEndpointR\x11preferredEndpoint\x12\x1f\n" +
	"\vis_selected\x18\x05 \x01(\bR\n" +
	"isSelected\"\x85\x03\n" +
	"\x0eDiscoveryState\x12G\n" +
	"\x05phase\x18\x01 \x01(\x0e21.io.goodkind.celltunnel.control.v1.DiscoveryPhaseR\x05phase\x12K\n" +
	"\bservices\x18\x02 \x03(\v2/.io.goodkind.celltunnel.control.v1.RelayServiceR\bservices\x12.\n" +
	"\x13selected_service_id\x18\x03 \x01(\tR\x11selectedServiceId\x12]\n" +
	"\x11selected_endpoint\x18\x04 \x01(\v20.io.goodkind.celltunnel.control.v1.RelayEndpointR\x10selectedEndpoint\x12N\n" +
	"\n" +
	"last_error\x18\x05 \x01(\v2/.io.goodkind.celltunnel.control.v1.ControlErrorR\tlastError\"Y\n" +
	"\x12RouteStateSnapshot\x12C\n" +
	"\x05state\x18\x01 \x01(\x0e2-.io.goodkind.celltunnel.control.v1.RouteStateR\x05state\"W\n" +
	"\x11PeerStateSnapshot\x12B\n" +
	"\x05state\x18\x01 \x01(\x0e2,.io.goodkind.celltunnel.control.v1.PeerStateR\x05state\"\xa3\x01\n" +
	"\x13TunnelStartSettings\x123\n" +
	"\x16wire_guard_config_path\x18\x01 \x01(\tR\x13wireGuardConfigPath\x12W\n" +
	"\x0erelay_endpoint\x18\x02 \x01(\v20.io.goodkind.celltunnel.control.v1.RelayEndpointR\rrelayEndpoint\"\x8c\x04\n" +
	"\fDaemonStatus\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12K\n" +
	"\x05route\x18\x02 \x01(\v25.io.goodkind.celltunnel.control.v1.RouteStateSnapshotR\x05route\x12H\n" +
	"\x04peer\x18\x03 \x01(\v24.io.goodkind.celltunnel.control.v1.PeerStateSnapshotR\x04peer\x12!\n" +
	"\fipv4_address\x18\x04 \x01(\tR\vipv4Address\x12!\n" +
	"\fipv6_address\x18\x05 \x01(\tR\vipv6Address\x12N\n" +
	"\n" +
	"last_error\x18\x06 \x01(\v2/.io.goodkind.celltunnel.control.v1.ControlErrorR\tlastError\x12O\n" +
	"\tdiscovery\x18\a \x01(\v21.io.goodkind.celltunnel.control.v1.DiscoveryStateR\tdiscovery\x12d\n" +
	"\x15active_relay_endpoint\x18\b \x01(\v20.io.goodkind.celltunnel.control.v1.RelayEndpointR\x13activeRelayEndpoint\"<\n" +
	"\x10EnvironmentCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"`\n" +
	"\x11EnvironmentReport\x12K\n" +
	"\x06checks\x18\x01 \x03(\v23.io.goodkind.celltunnel.control.v1.EnvironmentCheckR\x06checks\"\x0f\n" +
	"\rStatusRequest\"\xae\x01\n" +
	"\x0eStatusResponse\x12I\n" +
	"\x06status\x18\x01 \x01(\v2/.io.goodkind.celltunnel.control.v1.DaemonStatusH\x00R\x06status\x12G\n" +
	"\x05error\x18\x02 \x01(\v2/.io.goodkind.celltunnel.control.v1.ControlErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x0e\n" +
	"\fCheckRequest\"\xb2\x01\n" +
	"\rCheckResponse\x12N\n" +
	"\x06report\x18\x01 \x01(\v24.io.goodkind.celltunnel.control.v1.EnvironmentReportH\x00R\x06report\x12G\n" +
	"\x05error\x18\x02 \x01(\v2/.io.goodkind.celltunnel.control.v1.ControlErrorH\x00R\x05errorB\b\n" +
	"\x06result\"h\n" +
	"\x12StartTunnelRequest\x12R\n" +
	"\bsettings\x18\x01 \x01(\v26.io.goodkind.celltunnel.control.v1.TunnelStartSettingsR\bsettings\"\xb3\x01\n" +
	"\x13StartTunnelResponse\x12I\n" +
	"\x06status\x18\x01 \x01(\v2/.io.goodkind.celltunnel.control.v1.DaemonStatusH\x00R\x06status\x12G\n" +
	"\x05error\x18\x02 \x01(\v2/.io.goodkind.celltunnel.control.v1.ControlErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x13\n" +
	"\x11StopTunnelRequest\"\xb2\x01\n" +
	"\x12StopTunnelResponse\x12I\n" +
	"\x06status\x18\x01 \x01(\v2/.io.goodkind.celltunnel.control.v1.DaemonStatusH\x00R\x06status\x12G\n" +
	"\x05error\x18\x02 \x01(\v2/.io.goodkind.celltunnel.control.v1.ControlErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x1c\n" +
	"\x1aStartRelayDiscoveryRequest\"\xc3\x01\n" +
	"\x1bStartRelayDiscoveryResponse\x12Q\n" +
	"\tdiscovery\x18\x01 \x01(\v21.io.goodkind.celltunnel.control.v1.DiscoveryStateH\x00R\tdiscovery\x12G\n" +
	"\x05error\x18\x02 \x01(\v2/.io.goodkind.celltunnel.control.v1.ControlErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x1b\n" +
	"\x19StopRelayDiscoveryRequest\"\xc2\x01\n" +
	"\x1aStopRelayDiscoveryResponse\x12Q\n" +
	"\tdiscovery\x18\x01 \x01(\v21.io.goodkind.celltunnel.control.v1.DiscoveryStateH\x00R\tdiscovery\x12G\n" +
	"\x05error\x18\x02 \x01(\v2/.io.goodkind.celltunnel.control.v1.ControlErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x1a\n" +
	"\x18ListRelayServicesRequest\"\xc1\x01\n" +
	"\x19ListRelayServicesResponse\x12Q\n" +
	"\tdiscovery\x18\x01 \x01(\v21.io.goodkind.celltunnel.control.v1.DiscoveryStateH\x00R\tdiscovery\x12G\n" +
	"\x05error\x18\x02 \x01(\v2/.io.goodkind.celltunnel.control.v1.ControlErrorH\x00R\x05errorB\b\n" +
	"\x06result\":\n" +
	"\x19SelectRelayServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"\xc2\x01\n" +
	"\x1aSelectRelayServiceResponse\x12Q\n" +
	"\tdiscovery\x18\x01 \x01(\v21.io.goodkind.celltunnel.control.v1.DiscoveryStateH\x00R\tdiscovery\x12G\n" +
	"\x05error\x18\x02 \x01(\v2/.io.goodkind.celltunnel.control.v1.ControlErrorH\x00R\x05errorB\b\n" +
	"\x06result*a\n" +
	"\rAddressFamily\x12\x1e\n" +
	"\x1aADDRESS_FAMILY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ADDRESS_FAMILY_IPV4\x10\x01\x12\x17\n" +
	"\x13ADDRESS_FAMILY_IPV6\x10\x02*c\n" +
	"\n" +
	"RouteState\x12\x1b\n" +
	"\x17ROUTE_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ROUTE_STATE_NOT_INSTALLED\x10\x01\x12\x19\n" +
	"\x15ROUTE_STATE_INSTALLED\x10\x02*\x88\x01\n" +
	"\tPeerState\x12\x1a\n" +
	"\x16PEER_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PEER_STATE_NOT_SELECTED\x10\x01\x12\x1d\n" +
	"\x19PEER_STATE_RELAY_SELECTED\x10\x02\x12#\n" +
	"\x1fPEER_STATE_WIREGUARD_CONFIGURED\x10\x03*\xa3\x01\n" +
	"\x0eDiscoveryPhase\x12\x1f\n" +
	"\x1bDISCOVERY_PHASE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DISCOVERY_PHASE_STOPPED\x10\x01\x12\x1c\n" +
	"\x18DISCOVERY_PHASE_BROWSING\x10\x02\x12\x19\n" +
	"\x15DISCOVERY_PHASE_READY\x10\x03\x12\x1a\n" +
	"\x16DISCOVERY_PHASE_FAILED\x10\x04*\xf9\x02\n" +
	"\x10ControlErrorCode\x12\"\n" +
	"\x1eCONTROL_ERROR_CODE_UNSPECIFIED\x10\x00\x124\n" +
	"0CONTROL_ERROR_CODE_MISSING_WIREGUARD_CONFIG_PATH\x10\x01\x12/\n" +
	"+CONTROL_ERROR_CODE_RELAY_SELECTION_REQUIRED\x10\x02\x12.\n" +
	"*CONTROL_ERROR_CODE_RELAY_SERVICE_NOT_FOUND\x10\x03\x12,\n" +
	"(CONTROL_ERROR_CODE_DISCOVERY_UNAVAILABLE\x10\x04\x12-\n" +
	")CONTROL_ERROR_CODE_INVALID_RELAY_ENDPOINT\x10\x05\x12,\n" +
	"(CONTROL_ERROR_CODE_RUNTIME_START_FAILURE\x10\x06\x12\x1f\n" +
	"\x1bCONTROL_ERROR_CODE_INTERNAL\x10\a2\xba\b\n" +
	"\x14TunnelControlService\x12m\n" +
	"\x06Status\x120.io.goodkind.celltunnel.control.v1.StatusRequest\x1a1.io.goodkind.celltunnel.control.v1.StatusResponse\x12j\n" +
	"\x05Check\x12/.io.goodkind.celltunnel.control.v1.CheckRequest\x1a0.io.goodkind.celltunnel.control.v1.CheckResponse\x12|\n" +
	"\vStartTunnel\x125.io.goodkind.celltunnel.control.v1.StartTunnelRequest\x1a6.io.goodkind.celltunnel.control.v1.StartTunnelResponse\x12y\n" +
	"\n" +
	"StopTunnel\x124.io.goodkind.celltunnel.control.v1.StopTunnelRequest\x1a5.io.goodkind.celltunnel.control.v1.StopTunnelResponse\x12\x94\x01\n" +
	"\x13StartRelayDiscovery\x12=.io.goodkind.celltunnel.control.v1.StartRelayDiscoveryRequest\x1a>.io.goodkind.celltunnel.control.v1.StartRelayDiscoveryResponse\x12\x91\x01\n" +
	"\x12StopRelayDiscovery\x12<.io.goodkind.celltunnel.control.v1.StopRelayDiscoveryRequest\x1a=.io.goodkind.celltunnel.control.v1.StopRelayDiscoveryResponse\x12\x8e\x01\n" +
	"\x11ListRelayServices\x12;.io.goodkind.celltunnel.control.v1.ListRelayServicesRequest\x1a<.io.goodkind.celltunnel.control.v1.ListRelayServicesResponse\x12\x91\x01\n" +
	"\x12SelectRelayService\x12<.io.goodkind.celltunnel.control.v1.SelectRelayServiceRequest\x1a=.io.goodkind.celltunnel.control.v1.SelectRelayServiceResponseB?Z.celltunnel/daemon/internal/controlv1;controlv1\xba\x02\fCTControlV1_b\x06proto3"

var (
	file_io_goodkind_celltunnel_control_v1_control_proto_rawDescOnce sync.Once
	file_io_goodkind_celltunnel_control_v1_control_proto_rawDescData []byte
)

func file_io_goodkind_celltunnel_control_v1_control_proto_rawDescGZIP() []byte {
	file_io_goodkind_celltunnel_control_v1_control_proto_rawDescOnce.Do(func() {
		file_io_goodkind_celltunnel_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_io_goodkind_celltunnel_control_v1_control_proto_rawDesc), len(file_io_goodkind_celltunnel_control_v1_control_proto_rawDesc)))
	})
	return file_io_goodkind_celltunnel_control_v1_control_proto_rawDescData
}

var file_io_goodkind_celltunnel_control_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_io_goodkind_celltunnel_control_v1_control_proto_goTypes = []any{
	(AddressFamily)(0),                  // 0: io.goodkind.celltunnel.control.v1.AddressFamily
	(RouteState)(0),                     // 1: io.goodkind.celltunnel.control.v1.RouteState
	(PeerState)(0),                      // 2: io.goodkind.celltunnel.control.v1.PeerState
	(DiscoveryPhase)(0),                 // 3: io.goodkind.celltunnel.control.v1.DiscoveryPhase
	(ControlErrorCode)(0),               // 4: io.goodkind.celltunnel.control.v1.ControlErrorCode
	(*ControlError)(nil),                // 5: io.goodkind.celltunnel.control.v1.ControlError
	(*RelayEndpoint)(nil),               // 6: io.goodkind.celltunnel.control.v1.RelayEndpoint
	(*RelayServiceIdentity)(nil),        // 7: io.goodkind.celltunnel.control.v1.RelayServiceIdentity
	(*RelayService)(nil),                // 8: io.goodkind.celltunnel.control.v1.RelayService
	(*DiscoveryState)(nil),              // 9: io.goodkind.celltunnel.control.v1.DiscoveryState
	(*RouteStateSnapshot)(nil),          // 10: io.goodkind.celltunnel.control.v1.RouteStateSnapshot
	(*PeerStateSnapshot)(nil),           // 11: io.goodkind.celltunnel.control.v1.PeerStateSnapshot
	(*TunnelStartSettings)(nil),         // 12: io.goodkind.celltunnel.control.v1.TunnelStartSettings
	(*DaemonStatus)(nil),                // 13: io.goodkind.celltunnel.control.v1.DaemonStatus
	(*EnvironmentCheck)(nil),            // 14: io.goodkind.celltunnel.control.v1.EnvironmentCheck
	(*EnvironmentReport)(nil),           // 15: io.goodkind.celltunnel.control.v1.EnvironmentReport
	(*StatusRequest)(nil),               // 16: io.goodkind.celltunnel.control.v1.StatusRequest
	(*StatusResponse)(nil),              // 17: io.goodkind.celltunnel.control.v1.StatusResponse
	(*CheckRequest)(nil),                // 18: io.goodkind.celltunnel.control.v1.CheckRequest
	(*CheckResponse)(nil),               // 19: io.goodkind.celltunnel.control.v1.CheckResponse
	(*StartTunnelRequest)(nil),          // 20: io.goodkind.celltunnel.control.v1.StartTunnelRequest
	(*StartTunnelResponse)(nil),         // 21: io.goodkind.celltunnel.control.v1.StartTunnelResponse
	(*StopTunnelRequest)(nil),           // 22: io.goodkind.celltunnel.control.v1.StopTunnelRequest
	(*StopTunnelResponse)(nil),          // 23: io.goodkind.celltunnel.control.v1.StopTunnelResponse
	(*StartRelayDiscoveryRequest)(nil),  // 24: io.goodkind.celltunnel.control.v1.StartRelayDiscoveryRequest
	(*StartRelayDiscoveryResponse)(nil), // 25: io.goodkind.celltunnel.control.v1.StartRelayDiscoveryResponse
	(*StopRelayDiscoveryRequest)(nil),   // 26: io.goodkind.celltunnel.control.v1.StopRelayDiscoveryRequest
	(*StopRelayDiscoveryResponse)(nil),  // 27: io.goodkind.celltunnel.control.v1.StopRelayDiscoveryResponse
	(*ListRelayServicesRequest)(nil),    // 28: io.goodkind.celltunnel.control.v1.ListRelayServicesRequest
	(*ListRelayServicesResponse)(nil),   // 29: io.goodkind.celltunnel.control.v1.ListRelayServicesResponse
	(*SelectRelayServiceRequest)(nil),   // 30: io.goodkind.celltunnel.control.v1.SelectRelayServiceRequest
	(*SelectRelayServiceResponse)(nil),  // 31: io.goodkind.celltunnel.control.v1.SelectRelayServiceResponse
}
var file_io_goodkind_celltunnel_control_v1_control_proto_depIdxs = []int32{
	4,  // 0: io.goodkind.celltunnel.control.v1.ControlError.code:type_name -> io.goodkind.celltunnel.control.v1.ControlErrorCode
	0,  // 1: io.goodkind.celltunnel.control.v1.RelayEndpoint.address_family:type_name -> io.goodkind.celltunnel.control.v1.AddressFamily
	7,  // 2: io.goodkind.celltunnel.control.v1.RelayService.identity:type_name -> io.goodkind.celltunnel.control.v1.RelayServiceIdentity
	6,  // 3: io.goodkind.celltunnel.control.v1.RelayService.endpoints:type_name -> io.goodkind.celltunnel.control.v1.RelayEndpoint
	6,  // 4: io.goodkind.celltunnel.control.v1.RelayService.preferred_endpoint:type_name -> io.goodkind.celltunnel.control.v1.RelayEndpoint
	3,  // 5: io.goodkind.celltunnel.control.v1.DiscoveryState.phase:type_name -> io.goodkind.celltunnel.control.v1.DiscoveryPhase
	8,  // 6: io.goodkind.celltunnel.control.v1.DiscoveryState.services:type_name -> io.goodkind.celltunnel.control.v1.RelayService
	6,  // 7: io.goodkind.celltunnel.control.v1.DiscoveryState.selected_endpoint:type_name -> io.goodkind.celltunnel.control.v1.RelayEndpoint
	5,  // 8: io.goodkind.celltunnel.control.v1.DiscoveryState.last_error:type_name -> io.goodkind.celltunnel.control.v1.ControlError
	1,  // 9: io.goodkind.celltunnel.control.v1.RouteStateSnapshot.state:type_name -> io.goodkind.celltunnel.control.v1.RouteState
	2,  // 10: io.goodkind.celltunnel.control.v1.PeerStateSnapshot.state:type_name -> io.goodkind.celltunnel.control.v1.PeerState
	6,  // 11: io.goodkind.celltunnel.control.v1.TunnelStartSettings.relay_endpoint:type_name -> io.goodkind.celltunnel.control.v1.RelayEndpoint
	10, // 12: io.goodkind.celltunnel.control.v1.DaemonStatus.route:type_name -> io.goodkind.celltunnel.control.v1.RouteStateSnapshot
	11, // 13: io.goodkind.celltunnel.control.v1.DaemonStatus.peer:type_name -> io.goodkind.celltunnel.control.v1.PeerStateSnapshot
	5,  // 14: io.goodkind.celltunnel.control.v1.DaemonStatus.last_error:type_name -> io.goodkind.celltunnel.control.v1.ControlError
	9,  // 15: io.goodkind.celltunnel.control.v1.DaemonStatus.discovery:type_name -> io.goodkind.celltunnel.control.v1.DiscoveryState
	6,  // 16: io.goodkind.celltunnel.control.v1.DaemonStatus.active_relay_endpoint:type_name -> io.goodkind.celltunnel.control.v1.RelayEndpoint
	14, // 17: io.goodkind.celltunnel.control.v1.EnvironmentReport.checks:type_name -> io.goodkind.celltunnel.control.v1.EnvironmentCheck
	13, // 18: io.goodkind.celltunnel.control.v1.StatusResponse.status:type_name -> io.goodkind.celltunnel.control.v1.DaemonStatus
	5,  // 19: io.goodkind.celltunnel.control.v1.StatusResponse.error:type_name -> io.goodkind.celltunnel.control.v1.ControlError
	15, // 20: io.goodkind.celltunnel.control.v1.CheckResponse.report:type_name -> io.goodkind.celltunnel.control.v1.EnvironmentReport
	5,  // 21: io.goodkind.celltunnel.control.v1.CheckResponse.error:type_name -> io.goodkind.celltunnel.control.v1.ControlError
	12, // 22: io.goodkind.celltunnel.control.v1.StartTunnelRequest.settings:type_name -> io.goodkind.celltunnel.control.v1.TunnelStartSettings
	13, // 23: io.goodkind.celltunnel.control.v1.StartTunnelResponse.status:type_name -> io.goodkind.celltunnel.control.v1.DaemonStatus
	5,  // 24: io.goodkind.celltunnel.control.v1.StartTunnelResponse.error:type_name -> io.goodkind.celltunnel.control.v1.ControlError
	13, // 25: io.goodkind.celltunnel.control.v1.StopTunnelResponse.status:type_name -> io.goodkind.celltunnel.control.v1.DaemonStatus
	5,  // 26: io.goodkind.celltunnel.control.v1.StopTunnelResponse.error:type_name -> io.goodkind.celltunnel.control.v1.ControlError
	9,  // 27: io.goodkind.celltunnel.control.v1.StartRelayDiscoveryResponse.discovery:type_name -> io.goodkind.celltunnel.control.v1.DiscoveryState
	5,  // 28: io.goodkind.celltunnel.control.v1.StartRelayDiscoveryResponse.error:type_name -> io.goodkind.celltunnel.control.v1.ControlError
	9,  // 29: io.goodkind.celltunnel.control.v1.StopRelayDiscoveryResponse.discovery:type_name -> io.goodkind.celltunnel.control.v1.DiscoveryState
	5,  // 30: io.goodkind.celltunnel.control.v1.StopRelayDiscoveryResponse.error:type_name -> io.goodkind.celltunnel.control.v1.ControlError
	9,  // 31: io.goodkind.celltunnel.control.v1.ListRelayServicesResponse.discovery:type_name -> io.goodkind.celltunnel.control.v1.DiscoveryState
	5,  // 32: io.goodkind.celltunnel.control.v1.ListRelayServicesResponse.error:type_name -> io.goodkind.celltunnel.control.v1.ControlError
	9,  // 33: io.goodkind.celltunnel.control.v1.SelectRelayServiceResponse.discovery:type_name -> io.goodkind.celltunnel.control.v1.DiscoveryState
	5,  // 34: io.goodkind.celltunnel.control.v1.SelectRelayServiceResponse.error:type_name -> io.goodkind.celltunnel.control.v1.ControlError
	16, // 35: io.goodkind.celltunnel.control.v1.TunnelControlService.Status:input_type -> io.goodkind.celltunnel.control.v1.StatusRequest
	18, // 36: io.goodkind.celltunnel.control.v1.TunnelControlService.Check:input_type -> io.goodkind.celltunnel.control.v1.CheckRequest
	20, // 37: io.goodkind.celltunnel.control.v1.TunnelControlService.StartTunnel:input_type -> io.goodkind.celltunnel.control.v1.StartTunnelRequest
	22, // 38: io.goodkind.celltunnel.control.v1.TunnelControlService.StopTunnel:input_type -> io.goodkind.celltunnel.control.v1.StopTunnelRequest
	24, // 39: io.goodkind.celltunnel.control.v1.TunnelControlService.StartRelayDiscovery:input_type -> io.goodkind.celltunnel.control.v1.StartRelayDiscoveryRequest
	26, // 40: io.goodkind.celltunnel.control.v1.TunnelControlService.StopRelayDiscovery:input_type -> io.goodkind.celltunnel.control.v1.StopRelayDiscoveryRequest
	28, // 41: io.goodkind.celltunnel.control.v1.TunnelControlService.ListRelayServices:input_type -> io.goodkind.celltunnel.control.v1.ListRelayServicesRequest
	30, // 42: io.goodkind.celltunnel.control.v1.TunnelControlService.SelectRelayService:input_type -> io.goodkind.celltunnel.control.v1.SelectRelayServiceRequest
	17, // 43: io.goodkind.celltunnel.control.v1.TunnelControlService.Status:output_type -> io.goodkind.celltunnel.control.v1.StatusResponse
	19, // 44: io.goodkind.celltunnel.control.v1.TunnelControlService.Check:output_type -> io.goodkind.celltunnel.control.v1.CheckResponse
	21, // 45: io.goodkind.celltunnel.control.v1.TunnelControlService.StartTunnel:output_type -> io.goodkind.celltunnel.control.v1.StartTunnelResponse
	23, // 46: io.goodkind.celltunnel.control.v1.TunnelControlService.StopTunnel:output_type -> io.goodkind.celltunnel.control.v1.StopTunnelResponse
	25, // 47: io.goodkind.celltunnel.control.v1.TunnelControlService.StartRelayDiscovery:output_type -> io.goodkind.celltunnel.control.v1.StartRelayDiscoveryResponse
	27, // 48: io.goodkind.celltunnel.control.v1.TunnelControlService.StopRelayDiscovery:output_type -> io.goodkind.celltunnel.control.v1.StopRelayDiscoveryResponse
	29, // 49: io.goodkind.celltunnel.control.v1.TunnelControlService.ListRelayServices:output_type -> io.goodkind.celltunnel.control.v1.ListRelayServicesResponse
	31, // 50: io.goodkind.celltunnel.control.v1.TunnelControlService.SelectRelayService:output_type -> io.goodkind.celltunnel.control.v1.SelectRelayServiceResponse
	43, // [43:51] is the sub-list for method output_type
	35, // [35:43] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_io_goodkind_celltunnel_control_v1_control_proto_init() }
func file_io_goodkind_celltunnel_control_v1_control_proto_init() {
	if File_io_goodkind_celltunnel_control_v1_control_proto != nil {
		return
	}
	file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[12].OneofWrappers = []any{
		(*StatusResponse_Status)(nil),
		(*StatusResponse_Error)(nil),
	}
	file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[14].OneofWrappers = []any{
		(*CheckResponse_Report)(nil),
		(*CheckResponse_Error)(nil),
	}
	file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[16].OneofWrappers = []any{
		(*StartTunnelResponse_Status)(nil),
		(*StartTunnelResponse_Error)(nil),
	}
	file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[18].OneofWrappers = []any{
		(*StopTunnelResponse_Status)(nil),
		(*StopTunnelResponse_Error)(nil),
	}
	file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[20].OneofWrappers = []any{
		(*StartRelayDiscoveryResponse_Discovery)(nil),
		(*StartRelayDiscoveryResponse_Error)(nil),
	}
	file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[22].OneofWrappers = []any{
		(*StopRelayDiscoveryResponse_Discovery)(nil),
		(*StopRelayDiscoveryResponse_Error)(nil),
	}
	file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[24].OneofWrappers = []any{
		(*ListRelayServicesResponse_Discovery)(nil),
		(*ListRelayServicesResponse_Error)(nil),
	}
	file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes[26].OneofWrappers = []any{
		(*SelectRelayServiceResponse_Discovery)(nil),
		(*SelectRelayServiceResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_io_goodkind_celltunnel_control_v1_control_proto_rawDesc), len(file_io_goodkind_celltunnel_control_v1_control_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_io_goodkind_celltunnel_control_v1_control_proto_goTypes,
		DependencyIndexes: file_io_goodkind_celltunnel_control_v1_control_proto_depIdxs,
		EnumInfos:         file_io_goodkind_celltunnel_control_v1_control_proto_enumTypes,
		MessageInfos:      file_io_goodkind_celltunnel_control_v1_control_proto_msgTypes,
	}.Build()
	File_io_goodkind_celltunnel_control_v1_control_proto = out.File
	file_io_goodkind_celltunnel_control_v1_control_proto_goTypes = nil
	file_io_goodkind_celltunnel_control_v1_control_proto_depIdxs = nil
}
